version: '3.0'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_app
    command: /docker/start_app.sh
    volumes:
      - storage_app:/var/lib/mysql
      - ./webapp:/home/ishocon/webapp
    ports:
      - "443:443"

  storage_app:
    image: busybox
    volumes:
      - /var/lib/mysql

  bench:
    build:
      context: .
      dockerfile: Dockerfile_bench
    command: /docker/start_bench.sh
    volumes:
      - storage_bench:/var/lib/mysql
    links:
      - app

  storage_bench:
    image: busybox
    volumes:
      - /var/lib/mysql

volumes:
  storage_bench:
  storage_app:
